In [1]:
import numpy as np

In [2]:
A = np.array([[1,1],[1,0],[1,2]])

fang = np.array([[5,-3],[-3,3]])

P0 = np.dot(A,fang)
P = np.dot(P0,A.T)

P

array([[ 2,  2,  2],
       [ 2,  5, -1],
       [ 2, -1,  5]])

In [5]:
import torch

x = torch.randn(2, 3)
print(x)
print(x.add_(1))

tensor([[ 1.6291, -0.3394,  1.2241],
        [-0.7403,  1.5318,  0.1182]])
tensor([[2.6291, 0.6606, 2.2241],
        [0.2597, 2.5318, 1.1182]])


In [8]:
import numpy as np

x = np.linspace(0, 10, 5)
print(len(x))
print(x[-1]-x[-2])
print(x)

5
2.5
[ 0.   2.5  5.   7.5 10. ]


In [10]:
for i in range(5):
    print(i)

0
1
2
3
4
